Porting new cropping logic from hevcmeup2

diff --git a/av1meup2 b/av1meup2
--- a/av1meup2
+++ b/av1meup2
@@ -214,39 +214,61 @@ case "${BITDEPTH}" in
 esac
 
 if [ $CROP ]; then
-    if [ ! -x $CROPFINDER ]; then
-        exit 1
-    fi
-
+    echo "## Finding crop..."
     SEGMENTS=10
     CFOUTPUT=$($CROPFINDER -i "$INPUT" -s $SEGMENTS -d)
 
-    if [ $DEBUG ]; then
-        echo "$CFOUTPUT"
-    fi
+    [ $DEBUG ] && echo "$CFOUTPUT"
     CROP=$(echo "$CFOUTPUT" | tail -n1)
-    IFS=':' read width height left top <<< "$(echo "$CROP" | awk -F= '{print $2}')"
-    if [ $width -ne $INPUT_WIDTH ]; then
-        if [ $DEBUG ]; then
-            echo "Horizontal crop detected, checking for balance"
+    IFS=':' read width height left top <<< "$(echo "$CROP" | ${AWK} -F= '{print $2}')"
+    if [ $INPUT_WIDTH -eq $width ] && [ $INPUT_HEIGHT -eq $height ]; then
+        echo "## No crop detected"
+    else
+        if [ $height -eq 1072 ]; then 
+            [ $DEBUG ] && echo "The dumb eight pixel height crop, ignoring"
+            height=1080
+            top=0
+            CROP="crop=$width:1080:$left:0"
         fi
-        if [ $(( $width + 2 * $left )) -ne $INPUT_WIDTH ]; then
-            GUTTER_WIDTH=$(( ($INPUT_WIDTH - $width) / 2 ))
-            PAD="pad=$INPUT_WIDTH:$height:$GUTTER_WIDTH:0"
-            CROP="$CROP,$PAD"
-            if [ $DEBUG ]; then
-                echo "Unbalanced horizontal crop detected, evenly padding crop width ($width) back to input width ($INPUT_WIDTH) with gutters ($GUTTER_WIDTH)"
-                echo $CROP
+        if [ $width -ne $INPUT_WIDTH ] && [ $height -ne $INPUT_HEIGHT ]; then
+            [ $DEBUG ] && echo "Crop detected in both dimensions, that's not great"
+            if [ $left -gt $top ]; then
+                [ $DEBUG ] && echo "Maintaining input height ($INPUT_HEIGHT)"
+                if [ $(( $height + 2 * $top )) -ne $INPUT_HEIGHT ]; then
+                    GUTTERS=$(( ($INPUT_HEIGHT - $height) / 2 ))
+                    PAD="pad=$width:$INPUT_HEIGHT:0:$GUTTERS"
+                    CROP="$CROP,$PAD"
+                    [ $DEBUG ] && echo "Evenly padding crop height ($height) back to input height ($INPUT_HEIGHT) with gutters ($GUTTERS)"
+                else
+                    width=$INPUT_WIDTH
+                    CROP="crop=$width:$INPUT_HEIGHT:$left:0"
+                    [ $DEBUG ] && echo "Using original input height ($INPUT_HEIGHT)"
+                fi
+            elif [ $top -gt $left ]; then
+                [ $DEBUG ] && echo "Maintaining input width ($INPUT_WIDTH)"
+                if [ $(( $width + 2 * $left )) -ne $INPUT_WIDTH ]; then
+                    GUTTERS=$(( ($INPUT_WIDTH - $width) / 2 ))
+                    PAD="pad=$INPUT_WIDTH:$height:$GUTTERS:$top"
+                    CROP="$CROP,$PAD"
+                    [ $DEBUG ] && echo "Evenly padding crop width ($width) back to input width ($INPUT_WIDTH) with gutters ($GUTTERS)"
+                else
+                    width=$INPUT_WIDTH
+                    CROP="crop=$INPUT_WIDTH:$height:0:$top"
+                    [ $DEBUG ] && echo "Using original input width ($INPUT_WIDTH)"
+                fi
+            else
+                echo "## Ran out of cropping ideas. Look at this crop with your eyes, type it in with your hands."
+                echo "## This is what cropfinder delivered: ${CROP}"
+                exit 1
             fi
+        fi
+        if [ $INPUT_WIDTH -eq $width ] && [ $INPUT_HEIGHT -eq $height ]; then
+            echo "## After much consideration, no crop required"
         else
-            CROP="crop=$INPUT_WIDTH:$height:0:$top"
-            if [ $DEBUG ]; then
-                echo "Balanced horizontal crop detected, using input width ($INPUT_WIDTH) instead"
-                echo $CROP
-            fi
+            echo "## ${CROP}"
+            VF="${CROP}${VF:+,${VF}}"
         fi
     fi
-    VF="${CROP}${VF:+,${VF}}"
 fi
 
 if [ $AUDIO ]; then        
