use helper functions insteaad

diff --git a/av1meup2 b/av1meup2
--- a/av1meup2
+++ b/av1meup2
@@ -65,7 +65,7 @@ while [ $# -gt 0 ]; do
             shift;;
     --svt-params|--params)
             shift
-            SVT_PARAMS="${1}"
+            EXTRA_PARAMS="${1}"
             shift;;
     --svt-tune|--tune)
             shift
@@ -123,7 +123,6 @@ while [ $# -gt 0 ]; do
             exit;;
     *)
             echo "$0: invalid option ${1}"
-            echo "$0 -h for usage options"
             usage
             exit 1;;
     esac
@@ -436,7 +435,7 @@ G=240
 
 [ -z "$SVT_PRESET" ] && SVT_PRESET=7
 [ -z "$SVT_TUNE" ] && SVT_TUNE=2
-SVTAV1_PARAMS="${SVT_PARAMS:-tune=${SVT_TUNE}:enable-variance-boost=1:enable-qm=1:qm-min=0:enable-dlf=2}"
+paramsmunge "tune=${SVT_TUNE}:enable-variance-boost=1:enable-qm=1:qm-min=0:enable-dlf=2"
 
 if [ $COPY_HDR ]; then
     ## REFERENCES
@@ -459,11 +458,12 @@ if [ $COPY_HDR ]; then
     VIDEO_MIN_LUMINANCE_BC=$(echo "scale=4;$VIDEO_MIN_LUMINANCE" | ${BC})
 
     if [ "$VIDEO_COLOR_TRANSFER" = "arib-std-b67" ]; then #HLG
-        SVTAV1_PARAMS="${SVTAV1_PARAMS}:color-primaries=${VIDEO_COLOR_PRIMARIES}:transfer-characteristics=${VIDEO_COLOR_TRANSFER}:matrix-coefficients=${VIDEO_COLOR_SPACE_FIXED}"
+        paramsmunge "color-primaries=${VIDEO_COLOR_PRIMARIES}:transfer-characteristics=${VIDEO_COLOR_TRANSFER}:matrix-coefficients=${VIDEO_COLOR_SPACE_FIXED}"
+        paramsmunge "color-primaries=${VIDEO_COLOR_PRIMARIES}:transfer-characteristics=${VIDEO_COLOR_TRANSFER}:matrix-coefficients=${VIDEO_COLOR_SPACE_FIXED}"
     elif [ "$VIDEO_COLOR_TRANSFER" = "smpte2084" ]; then #HDR10
-        SVTAV1_PARAMS="${SVTAV1_PARAMS}:color-primaries=${VIDEO_COLOR_PRIMARIES}"
-        SVTAV1_PARAMS="${SVTAV1_PARAMS}:transfer-characteristics=${VIDEO_COLOR_TRANSFER}"
-        SVTAV1_PARAMS="${SVTAV1_PARAMS}:matrix-coefficients=${VIDEO_COLOR_SPACE_FIXED}"
+        paramsmunge "color-primaries=${VIDEO_COLOR_PRIMARIES}"
+        paramsmunge "transfer-characteristics=${VIDEO_COLOR_TRANSFER}"
+        paramsmunge "matrix-coefficients=${VIDEO_COLOR_SPACE_FIXED}"
 
         GREEN="${VIDEO_GREEN_X_BC},${VIDEO_GREEN_Y_BC}"
         BLUE="${VIDEO_BLUE_X_BC},${VIDEO_BLUE_Y_BC}"
@@ -472,7 +472,7 @@ if [ $COPY_HDR ]; then
         LUMINANCE="${VIDEO_MAX_LUMINANCE_BC},${VIDEO_MIN_LUMINANCE_BC}"
         CLL="${VIDEO_MAX_CONTENT},${VIDEO_MAX_AVERAGE}"
         
-        SVTAV1_PARAMS="${SVTAV1_PARAMS}:mastering-display=G(${GREEN})B(${BLUE})R(${RED})WP(${WHITE_POINT})L(${LUMINANCE}):content-light=${CLL}"
+        paramsmunge "mastering-display=G(${GREEN})B(${BLUE})R(${RED})WP(${WHITE_POINT})L(${LUMINANCE}):content-light=${CLL}"
     else
         echo "Unrecognized color transfer: ${VIDEO_COLOR_TRANSFER}"
         echo "Bailing out."
@@ -480,7 +480,11 @@ if [ $COPY_HDR ]; then
     fi
 fi
 
-VIDEO="-c:V libsvtav1 -pix_fmt ${PIXEL_FORMAT} -preset ${SVT_PRESET} -g ${G} -crf ${CRF} -svtav1-params ${SVTAV1_PARAMS}"
+if [ ! -z "$EXTRA_PARAMS" ]; then
+    paramsmunge "${EXTRA_PARAMS}" after
+fi
+
+VIDEO="-c:V libsvtav1 -pix_fmt ${PIXEL_FORMAT} -preset ${SVT_PRESET} -g ${G} -crf ${CRF} -svtav1-params ${PARAMS}"
 
 MAPS="-map 0 -map -0:d"
 TRAILERS="-c:s copy -max_muxing_queue_size 9999"
@@ -573,50 +577,26 @@ if [ $DEBUG ]; then
     esac
 fi
 
-if [[ "${INPUT##*.}" = ".mkv" ]]; then
+if [[ "${INPUT##*.}" == "mkv" ]]; then
     echo "## Stripping covers from input file..."
-    echo "$STRIPCOVERS \"${INPUT}\""
+    set -x
     $STRIPCOVERS "${INPUT}"
-    ## Can't check status on this, if there are no covers in the file, it exits 1
-    #if [ $? -eq 0 ]; then
-    #    echo "## Covers stripped."
-    #else
-    #    echo "## error stripping covers."
-    #    exit 1
-    #fi
+    { set +x; } 2>/dev/null
 fi
 
 echo "## Starting encode..."
 set -x
-nice -n 5 $FFMPEG -analyzeduration 100 -probesize 100M -i "$INPUT" $ENCODE_FLAGS "$OUTPUT"
+nice -n 5 $FFMPEG -analyzeduration 100 -probesize 100M -i "$INPUT" $ENCODE_FLAGS "$OUTPUT" && echo "## encode complete." || fail "encode error."
 { set +x; } 2>/dev/null
-if [ $? -eq 0 ]; then
-    echo "## encode complete."
-else
-    echo "## encoding error."
-    exit 1
-fi
 
-if [[ "${OUTPUT##*.}" = ".mkv" ]]; then
+if [[ "${OUTPUT##*.}" == "mkv" ]]; then
     echo "## Stripping tags from \"${OUTPUT}\"..."
     set -x
-    $STRIPTAGS "${OUTPUT}"
+    $STRIPTAGS "${OUTPUT}" && echo "## Tags stripped from \"${OUTPUT}\"" || fail "## error stripping tags from \"${OUTPUT}\""
     { set +x; } 2>/dev/null
-    if [ $? -eq 0 ]; then
-        echo "## Tags stripped from \"${OUTPUT}\""
-    else
-        echo "## error stripping tags from \"${OUTPUT}\""
-        exit 1
-    fi
 
     echo "## Adding stats to \"${OUTPUT}\"..."
     set -x
-    $ADDSTATS "${OUTPUT}"
+    $ADDSTATS "${OUTPUT}" && echo "## Stats added to \"${OUTPUT}\"" || fail "## error adding stats to \"${OUTPUT}\""
     { set +x; } 2>/dev/null
-    if [ $? -eq 0 ]; then
-        echo "## Stats added to \"${OUTPUT}\""
-    else
-        echo "## error adding stats to \"${OUTPUT}\""
-        exit 1
-    fi
 fi
