only do matroska things to matroska files

diff --git a/av1meup2 b/av1meup2
--- a/av1meup2
+++ b/av1meup2
@@ -570,20 +570,23 @@ if [ $DEBUG ]; then
     esac
 fi
 
-echo "## Stripping covers from input file..."
-echo "$STRIPCOVERS \"${INPUT}\""
-$STRIPCOVERS "${INPUT}"
-## Can't check status on this, if there are no covers in the file, it exits 1
-#if [ $? -eq 0 ]; then
-#    echo "## Covers stripped."
-#else
-#    echo "## error stripping covers."
-#    exit 1
-#fi
+if [[ "${INPUT##*.}" = ".mkv" ]]; then
+    echo "## Stripping covers from input file..."
+    echo "$STRIPCOVERS \"${INPUT}\""
+    $STRIPCOVERS "${INPUT}"
+    ## Can't check status on this, if there are no covers in the file, it exits 1
+    #if [ $? -eq 0 ]; then
+    #    echo "## Covers stripped."
+    #else
+    #    echo "## error stripping covers."
+    #    exit 1
+    #fi
+fi
 
 echo "## Starting encode..."
-echo "nice -n 5 $FFMPEG -analyzeduration 100M -probesize 100M -i \"$INPUT\" $ENCODE_FLAGS \"$OUTPUT\""
+set -x
 nice -n 5 $FFMPEG -analyzeduration 100M -probesize 100M -i "$INPUT" $ENCODE_FLAGS "$OUTPUT"
+{ set +x; } 2>/dev/null
 if [ $? -eq 0 ]; then
     echo "## encode complete."
 else
@@ -591,22 +594,26 @@ else
     exit 1
 fi
 
-echo "## Stripping tags from \"${OUTPUT}\"..."
-echo "$STRIPTAGS $(printf "%q" "${OUTPUT}")"
-$STRIPTAGS "${OUTPUT}"
-if [ $? -eq 0 ]; then
-    echo "## Tags stripped from \"${OUTPUT}\""
-else
-    echo "## error stripping tags from \"${OUTPUT}\""
-    exit 1
-fi
+if [[ "${OUTPUT##*.}" = ".mkv" ]]; then
+    echo "## Stripping tags from \"${OUTPUT}\"..."
+    set -x
+    $STRIPTAGS "${OUTPUT}"
+    { set +x; } 2>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "## Tags stripped from \"${OUTPUT}\""
+    else
+        echo "## error stripping tags from \"${OUTPUT}\""
+        exit 1
+    fi
 
-echo "## Adding stats to \"${OUTPUT}\"..."
-echo "$ADDSTATS $(printf "%q" "${OUTPUT}")"
-$ADDSTATS "${OUTPUT}" 
-if [ $? -eq 0 ]; then 
-    echo "## Stats added to \"${OUTPUT}\""
-else
-    echo "## error adding stats to \"${OUTPUT}\""
-    exit 1
+    echo "## Adding stats to \"${OUTPUT}\"..."
+    set -x
+    $ADDSTATS "${OUTPUT}"
+    { set +x; } 2>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "## Stats added to \"${OUTPUT}\""
+    else
+        echo "## error adding stats to \"${OUTPUT}\""
+        exit 1
+    fi
 fi
