Forgot to backport this into hevcmeup2, whoopsiedoodle

diff --git a/hevcmeup2 b/hevcmeup2
--- a/hevcmeup2
+++ b/hevcmeup2
@@ -318,6 +318,8 @@ if [ $CROP ]; then
     echo "## Finding crop..."
     SEGMENTS=10
     CFOUTPUT=$($CROPFINDER -i "$INPUT" -s $SEGMENTS -d)
+    [ $? -ne 0 ] && echo "<> cropfinder failed" && echo "<> cropfinder output: " && fail "$CFOUTPUT"
+    [ -z "$CFOUTPUT" ] && fail "<> cropfinder failed with no output"
 
     [ $DEBUG ] && echo "$CFOUTPUT"
     CROP=$(echo "$CFOUTPUT" | tail -n1)
