Stole pathmunge from redhat and used it for evil(?)

diff --git a/hevcmeup2 b/hevcmeup2
--- a/hevcmeup2
+++ b/hevcmeup2
@@ -33,6 +33,20 @@ Usage: ${0##*/} -i <INPUT FILE> -o <OUTPUT FILE>
 EOF
 }
 
+paramsmunge() {
+    case ":${X265_PARAMS}:" in
+        *:"$1":*)
+            ;;
+        *)
+            if [ "$2" = "after" ] ; then
+                X265_PARAMS=$(echo $X265_PARAMS:$1 | sed -e 's/^://g' -e 's/:$//g')
+            else
+                X265_PARAMS=$(echo $1:$X265_PARAMS | sed -e 's/^://g' -e 's/:$//g')
+            fi
+    esac
+}
+X265_PARAMS=
+
 while [ $# -gt 0 ]; do
     OPT="$1"
     case "${OPT}" in
@@ -240,6 +254,31 @@ case "${BITDEPTH}" in
         exit 1;;
 esac
 
+if [ $DOVIBL ] && [ $DOVIEL ]; then
+    echo "Cannot be both a BL and an EL, ass."
+    exit 1
+elif [ $DOVIBL ]; then
+    if [ $CROP ]; then
+        echo "Cannot crop Dolby Vision streams, disabling crop"
+        unset CROP
+    fi
+    ## implies copyhdr so we're gonna force it on here just in case
+    COPY_HDR=1
+    ## Probably working with elementary streams in this mode, so we need to set the framerate explicitly
+    FPS=$($MEDIAINFO ${INPUT} --output=JSON | jq -r '.media.track[] | select(."@type" == "Video" ).FrameRate')
+    paramsmunge "level-idc=5.1:high-tier=1:hrd=1:hrd-concat=1:info=1:fps=${FPS}:vbv-bufsize=85000:vbv-maxrate=85000:uhd-bd=1"
+elif [ $DOVIEL ]; then
+    if [ $CROP ]; then
+        echo "Cannot crop Dolby Vision streams, disabling crop"
+        unset CROP
+    fi
+    ## implies copyhdr so we're gonna force it on here just in case
+    COPY_HDR=1
+    ## Probably working with elementary streams in this mode, so we need to set the framerate explicitly
+    FPS=$($MEDIAINFO ${INPUT} --output=JSON | jq -r '.media.track[] | select(."@type" == "Video" ).FrameRate')
+    paramsmunge "level-idc=5.1:high-tier=1:hrd=1:hrd-concat=1:info=1:fps=${FPS}:vbv-bufsize=10000:vbv-maxrate=10000:uhd-bd=1"
+fi
+
 if [ $CROP ]; then
     echo "## Finding crop..."
     SEGMENTS=10
@@ -426,51 +465,31 @@ else
 fi
 
 if [ $MELTON ]; then
-    if [ ! -z "${MELTON_BITRATE}" ]; then 
-        CRFMAX=25
-        VBVMAX=${MELTON_BITRATE}
-        VBVBUF=$(expr $MELTON_BITRATE \* 2)
-        QPMAX=34
-    elif [ "$INPUT_WIDTH" -gt 1280 ]; then
-        CRFMAX=25
-        VBVMAX=24000
-        VBVBUF=48000
-        QPMAX=34
-    elif [ "$INPUT_WIDTH" -gt 854 ]; then
-        CRFMAX=29
-        VBVMAX=3000
-        VBVBUF=6000
-        QPMAX=34
-    else
-        CRFMAX=33
-        VBVMAX=1500
-        VBVBUF=3000
-        QPMAX=34
-    fi
-    X265_PARAMS="crf=1:vbv-maxrate=${VBVMAX}:vbv-bufsize=${VBVBUF}:crf-max=${CRFMAX}:qpmax=${QPMAX}:log-level=error"
+    echo "I'm disabling this for now cause I never use it and I don't want to account for it anymore. Sorry."
+    #if [ ! -z "${MELTON_BITRATE}" ]; then 
+    #    CRFMAX=25
+    #    VBVMAX=${MELTON_BITRATE}
+    #    VBVBUF=$(expr $MELTON_BITRATE \* 2)
+    #    QPMAX=34
+    #elif [ "$INPUT_WIDTH" -gt 1280 ]; then
+    #    CRFMAX=25
+    #    VBVMAX=24000
+    #    VBVBUF=48000
+    #    QPMAX=34
+    #elif [ "$INPUT_WIDTH" -gt 854 ]; then
+    #    CRFMAX=29
+    #    VBVMAX=3000
+    #    VBVBUF=6000
+    #    QPMAX=34
+    #else
+    #    CRFMAX=33
+    #    VBVMAX=1500
+    #    VBVBUF=3000
+    #    QPMAX=34
+    #fi
+    #X265_PARAMS="crf=1:vbv-maxrate=${VBVMAX}:vbv-bufsize=${VBVBUF}:crf-max=${CRFMAX}:qpmax=${QPMAX}:log-level=error"
 else
-    X265_PARAMS="crf=${CRF}"
-fi
-
-if [ ! -z "$EXTRA_X265_PARAMS" ]; then
-    X265_PARAMS="${X265_PARAMS}:${EXTRA_X265_PARAMS}"
-fi
-
-if [ $DOVIBL ] && [ $DOVIEL ]; then
-    echo "Cannot be both a BL and an EL, ass."
-    exit 1
-elif [ $DOVIBL ]; then
-    ## implies copyhdr so we're gonna force it on here just in case
-    COPY_HDR=1
-    ## Probably working with elementary streams in this mode, so we need to set the framerate explicitly
-    FPS=$($MEDIAINFO ${INPUT} --output=JSON | jq -r '.media.track[] | select(."@type" == "Video" ).FrameRate')
-    X265_PARAMS="${X265_PARAMS}:level-idc=5.1:high-tier=1:hrd=1:hrd-concat=1:info=1:fps=${FPS}:vbv-bufsize=85000:vbv-maxrate=85000:uhd-bd=1";
-elif [ $DOVIEL ]; then
-    ## implies copyhdr so we're gonna force it on here just in case
-    COPY_HDR=1
-    ## Probably working with elementary streams in this mode, so we need to set the framerate explicitly
-    FPS=$($MEDIAINFO ${INPUT} --output=JSON | jq -r '.media.track[] | select(."@type" == "Video" ).FrameRate')
-    X265_PARAMS="${X265_PARAMS}:level-idc=5.1:high-tier=1:hrd=1:hrd-concat=1:info=1:fps=${FPS}:vbv-bufsize=10000:vbv-maxrate=10000:uhd-bd=1";
+    paramsmunge "crf=${CRF}"
 fi
 
 if [ $COPY_HDR ]; then
@@ -478,9 +497,13 @@ if [ $COPY_HDR ]; then
     # https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/
     ## THIS IS A DANK ASS TRICK THAT MAKES VARIABLES OUT OF ALL THE VIDEO METADATA
     eval "$($FFPROBE -hide_banner -loglevel warning -select_streams v -print_format json -show_frames -read_intervals "%+#1" -show_entries "frame=hdr_format,color_range,color_space,color_primaries,color_transfer,side_data_list,pix_fmt" -i "${INPUT}" | ${GREP} -v -e frames -e '{' -e '\[' -e '}' -e '\]' -e 'side' | ${SED} -e 's/^\ *//g' -e 's/^"//g' -e 's/\":/:/g' -e 's/:\ /=/g' -e 's/,//g' -e 's/^/video_/g' -e 's/^.*=/\U&/g')"
-    X265_PARAMS="${X265_PARAMS}:hdr-opt=1:repeat-headers=1:colorprim=${VIDEO_COLOR_PRIMARIES}:transfer=${VIDEO_COLOR_TRANSFER}:colormatrix=${VIDEO_COLOR_SPACE}:master-display=G(${VIDEO_GREEN_X%/*},${VIDEO_GREEN_Y%/*})B(${VIDEO_BLUE_X%/*},${VIDEO_BLUE_Y%/*})R(${VIDEO_RED_X%/*},${VIDEO_RED_Y%/*})WP(${VIDEO_WHITE_POINT_X%/*},${VIDEO_WHITE_POINT_Y%/*})L(${VIDEO_MAX_LUMINANCE%/*},${VIDEO_MIN_LUMINANCE%/*}):max-cll=${VIDEO_MAX_CONTENT},${VIDEO_MAX_AVERAGE}"
+    paramsmunge "hdr-opt=1:repeat-headers=1:colorprim=${VIDEO_COLOR_PRIMARIES}:transfer=${VIDEO_COLOR_TRANSFER}:colormatrix=${VIDEO_COLOR_SPACE}:master-display=G(${VIDEO_GREEN_X%/*},${VIDEO_GREEN_Y%/*})B(${VIDEO_BLUE_X%/*},${VIDEO_BLUE_Y%/*})R(${VIDEO_RED_X%/*},${VIDEO_RED_Y%/*})WP(${VIDEO_WHITE_POINT_X%/*},${VIDEO_WHITE_POINT_Y%/*})L(${VIDEO_MAX_LUMINANCE%/*},${VIDEO_MIN_LUMINANCE%/*}):max-cll=${VIDEO_MAX_CONTENT},${VIDEO_MAX_AVERAGE}"
     ## I'm sneaky forcing the fast analysis preset cause the only HDR I encode is 4k and 4k is so painfully slow already that I'll take the half-point drop in VMAF to shave 40% off the encoding time
     PRESET="fast"
+fi
+
+if [ ! -z "$EXTRA_X265_PARAMS" ]; then
+    paramsmunge "${EXTRA_x265_PARAMS}" after
 fi
 
 MAPS="-map 0 -map -0:d"
