Support cropping for dolby vision streams

diff --git a/visionary b/visionary
--- a/visionary
+++ b/visionary
@@ -20,6 +20,7 @@ Usage: ${0##*/} -i <INPUT FILE>
 --svtfilmgrain:     engage svt-av1 grain analysis/reconstruction
 --av1:              HIGHLY EXPERIMENTAL SUPPORT FOR AV1
 --dual:             Run both an hevc AND an av1 encode in one pass (more efficient)
+--crop:             crop input video, remove offsets from dovi RPUs (no HDR10+)
 --debug:            print debugging information
 
 EOF
@@ -30,6 +31,7 @@ AV1=0
 KEEP=0
 VERIFY=0
 DENOISE=0
+CROP=0
 
 while [ $# -gt 0 ]; do
     OPT="${1}"
@@ -91,6 +93,9 @@ while [ $# -gt 0 ]; do
     --dual)
         AV1=1
         shift;;
+    --crop)
+        CROP=1
+        shift;;
     --debug)
         DEBUG=1
         shift;;
@@ -110,7 +115,7 @@ SELF_DIR=`dirname ${SELF_FULLPATH}`
 MODULE_COLLECTION="visionary"
 TOOLS=(mkvmerge mkvextract mediainfo grep awk dovi_tool hdr10plus_tool jq mkfifo base64 ffprobe ffmpeg SvtAv1EncApp sed bc column)
 [ ${VERIFY} -eq 1 ] && TOOLS+=(dvesverifier)
-SCRIPTS=(hevcmeup2 av1meup2 striptags stripcovers addstats)
+SCRIPTS=(hevcmeup2 av1meup2 striptags stripcovers addstats cropfinder)
 [ -n "${AUDIO}" ] && SCRIPTS+=(audiovise)
 
 if [ ! -r ${SELF_DIR}/toolchecker ]; then
@@ -207,6 +212,10 @@ fi
 if [[ "${FORMATCOMPAT}" =~ "HDR10+" ]]; then
     ISHDR10P=1
     echo ">> HDR10+ metadata present"
+    if [ $CROP == 1 ]; then
+        echo "<> Cannot crop with HDR10+"
+        exit 1
+    fi
 fi
 echo
 
@@ -216,7 +225,7 @@ if [ ${DEBUG:-0} -eq 1 ]; then
     echo
     echo "<< VARIABLE STATE:"
     echo "<< -----------------"
-    for var in INPUT FPS HDRFORMAT FORMATCOMPAT DURATION FRAME_COUNT BITRATE SIZE ISDOVI ISHDR10P HDRSUM OUTPUT HEVC AV1 KEEP VERIFY DENOISE X265CRF X265PRESET X265TUNE SVTCRF SVTPRESET SVTTUNE SVTFILMGRAIN AUDIO SVTAV1_FORK SVTAV1_VERSION FIFO BL BL10P EL RPU RPU_8 HDR10P BLX265 WITH_RPU AV1_IVF REMUXED; do
+    for var in INPUT FPS HDRFORMAT FORMATCOMPAT DURATION FRAME_COUNT BITRATE SIZE ISDOVI ISHDR10P HDRSUM OUTPUT HEVC AV1 KEEP VERIFY DENOISE X265CRF X265PRESET X265TUNE SVTCRF SVTPRESET SVTTUNE SVTFILMGRAIN AUDIO CROP SVTAV1_FORK SVTAV1_VERSION FIFO BL BL10P EL RPU RPU_8 HDR10P BLX265 WITH_RPU AV1_IVF REMUXED; do
         [ -n "${!var}" ] && echo "<< $var,${!var}" || echo "<< $var,<unset>"
     done | ${COLUMN} --separator , --table --table-name "VARIABLE STATE" --output-separator " | "
     echo
@@ -303,7 +312,7 @@ if [ ${ISDOVI} -eq 1 ]; then
             ## extract and convert the profile 7 RPU to a profile 8 RPU
             echo ">> Extracting RPU in profile 8 format"; echo
             set -x
-            ${DOVI_TOOL} --mode 2 extract-rpu --input ${EL} --rpu-out ${RPU_8} || fail "<> RPU extraction failed."
+            ${DOVI_TOOL} --mode 2 ${CROP:+--crop} extract-rpu --input ${EL} --rpu-out ${RPU_8} || fail "<> RPU extraction failed."
             { set +x; } 2>/dev/null
             echo
             ;;
@@ -323,7 +332,7 @@ if [ ${ISDOVI} -eq 1 ]; then
             echo ">> Extracting RPU"; echo
             set -x
             ${MKVEXTRACT} "${INPUT}" tracks 0:"${FIFO}" &
-            ${DOVI_TOOL} extract-rpu --rpu-out "${RPU_8}" - <"${FIFO}" || fail "<> RPU extraction failed."
+            ${DOVI_TOOL} ${CROP:+--crop} extract-rpu --rpu-out "${RPU_8}" - <"${FIFO}" || fail "<> RPU extraction failed."
             { set +x; } 2>/dev/null
             echo
             ;;
@@ -376,6 +385,10 @@ rm "${FIFO}"
 { set +x; } 2>/dev/null
 echo
 
+if [ ${CROP} -eq 1 ]; then
+    [ ${DEBUG:-0} -eq 1 ] && echo ">> finding crop from input file"
+    VFCROP=$($CROPFINDER -i "${INPUT}")
+fi
 ## let's cook this sucker
 echo ">> Starting encode(s)..."; echo
 
@@ -393,6 +406,7 @@ if [ ${AV1} -eq 1 ]; then
     fi
     [ ${ISDOVI} -eq 1 ] && OPTIONS="${OPTIONS} --rpufile ${RPU_8}"
     [ ${ISHDR10P} -eq 1 ] && OPTIONS="${OPTIONS} --hdr10pfile ${HDR10P}"
+    [ ${CROP} -eq 1 ] && OPTIONS="${OPTIONS} --vf ${VFCROP}"
     if [ "${DENOISE}" == "all" ] || [ "${DENOISE}" == "svt" ]; then
         OPTIONS="${OPTIONS} --denoise"
     fi
@@ -408,7 +422,7 @@ fi
 if [ ${HEVC} -eq 1 ]; then
     echo ">> Starting X265 encode..."
     OPTIONS="--input ${BL} --output ${BLX265} ${X265CRF:+--crf $X265CRF} ${X265PRESET:+--preset $PRESET} ${X265TUNE:+--tune $TUNE}"
-    if [ "${FPS_NUM}" != "" ] && [ "${FPS_DEN}" != "" ]; then
+    if [ "${FPS_NUM}" != "" ] && [ "${FPS_DEN}" != "" ] && [ "${FPS_NUM}" != "null" ] && [ "${FPS_DEN}" != "null" ]; then
         OPTIONS="${OPTIONS} --fps ${FPS_NUM}/${FPS_DEN}"
     elif [ "${FPS}" != "" ]; then
         OPTIONS="${OPTIONS} --fps ${FPS}"
@@ -417,6 +431,7 @@ if [ ${HEVC} -eq 1 ]; then
         exit 1
     fi
     [ ${ISDOVI} -eq 1 ] && OPTIONS="$OPTIONS --dovi-bl"
+    [ ${CROP} -eq 1 ] && OPTIONS="${OPTIONS} --vf ${VFCROP}"
     if [ "${DENOISE}" == "all" ] || [ "${DENOISE}" == "x265" ]; then
         OPTIONS="${OPTIONS} --denoise"
     fi
